# Generated by Django 4.2.5 on 2025-05-05 13:29


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0025_formula_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('version_software', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActaRecibidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActaObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.CreateModel(
            name='ActaObjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.proyecto'),
        ),
        migrations.CreateModel(
            name='ActaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
    ]
