# Generated by Django 4.2.5 on 2025-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0026_actaentrega_proyecto_actarecibidopor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corresponsal_consignacion',
            name='imei',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='corresponsal_consignacion',
            name='min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='corresponsal_consignacion',
            name='planilla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
