# Generated by Django 4.2.5 on 2025-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0027_corresponsal_consignacion_imei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
